In [1]:
import pandas as pd

In [2]:
file = pd.read_csv("C:/Users/ramiz/Desktop/test.csv")

In [3]:
file.head()

,wkt_geom,fid,osm_id,name,type,oneway,distance,angle,timestamp
0,MultiLineString ((10413524.18912726454436779 4...,1,4885624,Galata Köprüsü,primary,1,460,29.319016,2022-01-15T20:00:32.000
1,MultiLineString ((10413524.18912726454436779 4...,2,4885624,Galata Köprüsü,primary,1,440,29.319016,2022-01-15T20:00:31.000
2,MultiLineString ((10413524.18912726454436779 4...,3,4885624,Galata Köprüsü,primary,1,420,29.319016,2022-01-15T20:00:30.000
3,MultiLineString ((10413524.18912726454436779 4...,4,4885624,Galata Köprüsü,primary,1,400,29.319016,2022-01-15T20:00:28.000
4,MultiLineString ((10413524.18912726454436779 4...,5,4885624,Galata Köprüsü,primary,1,380,29.319016,2022-01-15T20:00:27.000

In [11]:
file.dtypes

wkt_geom      object
fid            int64
osm_id         int64
name          object
type          object
oneway         int64
distance       int64
angle        float64
timestamp     object
dtype: object

In [41]:
lyrics = pd.read_csv('C:/Users/ramiz/Desktop/4th class 1st term/NLP/proje/new_trial/lyrics-data.csv')

In [42]:
lyrics.head()

,ALink,SName,SLink,Lyric,Idiom
0,/10000-maniacs/,More Than This,/10000-maniacs/more-than-this.html,I could feel at the time. There was no way of ...,ENGLISH
1,/10000-maniacs/,Because The Night,/10000-maniacs/because-the-night.html,"Take me now, baby, here as I am. Hold me close...",ENGLISH
2,/10000-maniacs/,These Are Days,/10000-maniacs/these-are-days.html,These are. These are days you'll remember. Nev...,ENGLISH
3,/10000-maniacs/,A Campfire Song,/10000-maniacs/a-campfire-song.html,"A lie to say, ""O my mountain has coal veins an...",ENGLISH
4,/10000-maniacs/,Everyday Is Like Sunday,/10000-maniacs/everyday-is-like-sunday.html,Trudging slowly over wet sand. Back to the ben...,ENGLISH

In [43]:
dataset = lyrics.join(artists.set_index('Link'), on='ALink')

In [44]:
dataset = dataset.dropna()

In [45]:
dataset.head()

,ALink,SName,SLink,Lyric,Idiom,Artist,Songs,Popularity,Genre,Genres
0,/10000-maniacs/,More Than This,/10000-maniacs/more-than-this.html,I could feel at the time. There was no way of ...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...
0,/10000-maniacs/,More Than This,/10000-maniacs/more-than-this.html,I could feel at the time. There was no way of ...,ENGLISH,10000 Maniacs,110.0,0.3,Pop,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...
1,/10000-maniacs/,Because The Night,/10000-maniacs/because-the-night.html,"Take me now, baby, here as I am. Hold me close...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...
1,/10000-maniacs/,Because The Night,/10000-maniacs/because-the-night.html,"Take me now, baby, here as I am. Hold me close...",ENGLISH,10000 Maniacs,110.0,0.3,Pop,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...
2,/10000-maniacs/,These Are Days,/10000-maniacs/these-are-days.html,These are. These are days you'll remember. Nev...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...

In [46]:
dataset['Idiom'].value_counts()

ENGLISH           124229
PORTUGUESE         93110
SPANISH             4950
ITALIAN              635
FRENCH               407
GERMAN               332
KINYARWANDA           89
SWEDISH               27
FINNISH               24
ESTONIAN              24
INDONESIAN            14
GALICIAN              14
IRISH                 10
DANISH                 9
CROATIAN               9
HAITIAN_CREOLE         9
BASQUE                 8
SUNDANESE              8
TAGALOG                7
SWAHILI                7
NORWEGIAN              7
CATALAN                5
NYANJA                 4
RUSSIAN                4
CEBUANO                4
DUTCH                  4
SERBIAN                4
MALAY                  3
SESOTHO                2
KURDISH                2
JAPANESE               2
MALAGASY               2
TURKISH                2
ARABIC                 2
SLOVAK                 1
CZECH                  1
SLOVENIAN              1
BOSNIAN                1
WELSH                  1
HMONG                  1
GANDA                  1
KOREAN                 1
HUNGARIAN              1
POLISH                 1
AFRIKAANS              1
ROMANIAN               1
Name: Idiom, dtype: int64

In [47]:
dataset = dataset.loc[dataset['Idiom'] == 'ENGLISH']

In [48]:
dataset.drop_duplicates(subset=['SName'], inplace=True)

In [49]:
dataset = dataset.join(dataset['Genres'].str.split(pat=';', expand=True).add_prefix('Genre'))

In [50]:
dataset.head()

,ALink,SName,SLink,Lyric,Idiom,Artist,Songs,Popularity,Genre,Genres,...,Genre57,Genre58,Genre59,Genre60,Genre61,Genre62,Genre63,Genre64,Genre65,Genre66
0,/10000-maniacs/,More Than This,/10000-maniacs/more-than-this.html,I could feel at the time. There was no way of ...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
1,/10000-maniacs/,Because The Night,/10000-maniacs/because-the-night.html,"Take me now, baby, here as I am. Hold me close...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
2,/10000-maniacs/,These Are Days,/10000-maniacs/these-are-days.html,These are. These are days you'll remember. Nev...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
3,/10000-maniacs/,A Campfire Song,/10000-maniacs/a-campfire-song.html,"A lie to say, ""O my mountain has coal veins an...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
4,/10000-maniacs/,Everyday Is Like Sunday,/10000-maniacs/everyday-is-like-sunday.html,Trudging slowly over wet sand. Back to the ben...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None

In [51]:
dataset.head()

,ALink,SName,SLink,Lyric,Idiom,Artist,Songs,Popularity,Genre,Genres,...,Genre57,Genre58,Genre59,Genre60,Genre61,Genre62,Genre63,Genre64,Genre65,Genre66
0,/10000-maniacs/,More Than This,/10000-maniacs/more-than-this.html,I could feel at the time. There was no way of ...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
1,/10000-maniacs/,Because The Night,/10000-maniacs/because-the-night.html,"Take me now, baby, here as I am. Hold me close...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
2,/10000-maniacs/,These Are Days,/10000-maniacs/these-are-days.html,These are. These are days you'll remember. Nev...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
3,/10000-maniacs/,A Campfire Song,/10000-maniacs/a-campfire-song.html,"A lie to say, ""O my mountain has coal veins an...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
4,/10000-maniacs/,Everyday Is Like Sunday,/10000-maniacs/everyday-is-like-sunday.html,Trudging slowly over wet sand. Back to the ben...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None

In [52]:
dataset = dataset[dataset['Genre0'].isin(['Rock', 'Pop', 'Hip Hop', 'Indie'])]

In [53]:
dataset.head()

,ALink,SName,SLink,Lyric,Idiom,Artist,Songs,Popularity,Genre,Genres,...,Genre57,Genre58,Genre59,Genre60,Genre61,Genre62,Genre63,Genre64,Genre65,Genre66
0,/10000-maniacs/,More Than This,/10000-maniacs/more-than-this.html,I could feel at the time. There was no way of ...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
1,/10000-maniacs/,Because The Night,/10000-maniacs/because-the-night.html,"Take me now, baby, here as I am. Hold me close...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
2,/10000-maniacs/,These Are Days,/10000-maniacs/these-are-days.html,These are. These are days you'll remember. Nev...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
3,/10000-maniacs/,A Campfire Song,/10000-maniacs/a-campfire-song.html,"A lie to say, ""O my mountain has coal veins an...",ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None
4,/10000-maniacs/,Everyday Is Like Sunday,/10000-maniacs/everyday-is-like-sunday.html,Trudging slowly over wet sand. Back to the ben...,ENGLISH,10000 Maniacs,110.0,0.3,Rock,Rock; Pop; Electronica; Dance; J-Pop/J-Rock; G...,...,None,None,None,None,None,None,None,None,None,None

In [55]:
dataset.reindex(['Lyric', 'Genre0'], axis=1)

                                                    Lyric Genre0
0       I could feel at the time. There was no way of ...   Rock
1       Take me now, baby, here as I am. Hold me close...   Rock
2       These are. These are days you'll remember. Nev...   Rock
3       A lie to say, "O my mountain has coal veins an...   Rock
4       Trudging slowly over wet sand. Back to the ben...   Rock
...                                                   ...    ...
153843  Every avenue in Tokyo. Is saying that I'm gonn...    Pop
153848  Only when you're close. Only when you're close...    Pop
153859  A dream like this. Not something. You wish for...    Pop
153861  Aah, yeah yeah. I see the spotlight in my drea...    Pop
153867  Ha, a-plus on the track. Ha, ha, ha, uh, yeah....    Pop

[39878 rows x 2 columns]

In [56]:
dataset.dropna(inplace=True)

In [57]:
dataset.to_csv('train2.csv', header=True, index=False)